### ISSUE TITLE
Tried to run the example but I get an angular js injection error. 

### ISSUE THREAD

**Issue by grchis** [philipsorst/angular-rest-springsecurity#29]
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module exampleApp due to:
Error: [$injector:nomod] Module 'exampleApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.2/$injector/nomod?p0=exampleApp
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:1958:17
    at ensure (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:1882:38)
    at module (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:1956:14)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:4364:22
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:336:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:4348:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:4274:11)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:1630:20)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js:1651:12)
http://errors.angularjs.org/1.4.2/$injector/modulerr?p0=exampleApp&p1=Error….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.2%2Fangular.js%3A1651%3A12)(anonymous function) @ angular.js:68(anonymous function) @ angular.js:4387forEach @ angular.js:336loadModules @ angular.js:4348createInjector @ angular.js:4274doBootstrap @ angular.js:1630bootstrap @ angular.js:1651angularInit @ angular.js:1545(anonymous function) @ angular.js:28361fire @ jquery.js:3099self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433

**Comment by philipsorst** [comment]
Just checked back, it is working for me. Please make sure you do not have an adblocker enabled or anything that might prevent loading external resources.
